//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscrito
    {
        public int id { get; set; }
        public Nullable<int> categoriaId { get; set; }
        public Nullable<System.DateTime> dataInscricao { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string nome { get; set; }
        public byte[] foto { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
